// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlsrnOgjf77FI_XL1EfS_PyxDyH1_m50',
    appId: '1:646935299162:android:04bafdc9c0176ebbfc4463',
    messagingSenderId: '646935299162',
    projectId: 'orbit-26122025',
    storageBucket: 'orbit-26122025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6sQgpj_V_JqsNBHPfUkpy44irb6323Ts',
    appId: '1:646935299162:ios:527019c38a56505ffc4463',
    messagingSenderId: '646935299162',
    projectId: 'orbit-26122025',
    storageBucket: 'orbit-26122025.firebasestorage.app',
    androidClientId: '646935299162-0g8sggiaqc3lc8fpjmpoc6notda60sjn.apps.googleusercontent.com',
    iosClientId: '646935299162-qio5a98l7gsnkgo17vbpnviion6jjv83.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
